package generated;

import org.springframework.context.MessageSource;
import org.springframework.context.MessageSourceAware;
import org.springframework.stereotype.Component;

import com.company.project.util.I18nNamedMessageResolver;

//
// auto generated by Build.java, Please do not modify it directly.
// 
// if has error, you can delete this file.
//
@Component
public class I18nKeys implements MessageSourceAware{

	public static I18nNamedMessageResolver messageSource;

	@Override
	public void setMessageSource(MessageSource value) {
		messageSource = new I18nNamedMessageResolver(value);
	}


<#list i18nEnMap?keys as key>

	<#assign newKey = key?replace('.', '_')?replace('-', '_')>
	// en: ${i18nEnMap[key]}
	// zh_CN: ${i18nZhCNMap[key]}
	public static String i18n_${newKey} = "${key}";
</#list>

<#list i18nEnMap?keys as key>

	<#assign newKey = key?replace('.', '_')?replace('-', '_')>
	// en: ${i18nEnMap[key]}
	// zh_CN: ${i18nZhCNMap[key]}
	public static String i18n_${newKey}(<#list i18nValueParams[key]?keys as param>String ${param}<#if param_has_next>,</#if></#list>){
		String[] params = new String[]{<#list i18nValueParams[key]?keys as param>"${param}",${param}<#if param_has_next>,</#if></#list>};
		return messageSource.getNamedMessage(i18n_${newKey},params);
	}
</#list>
}