package generated;

//
// auto generated by Build.java, Please do not modify it directly.
//

public class I18nKeys {
<#list i18nEnMap?keys as key>

	<#assign newKey = key?replace('.', '_')?replace('-', '_')>
	// en: ${i18nEnMap[key]}
	// zh_CN: ${i18nZhCNMap[key]}
	public static String i18n_${newKey} = "${key}";
</#list>
}