package generated;

import org.springframework.context.MessageSource;
import org.springframework.context.MessageSourceAware;
import org.springframework.stereotype.Component;

import com.company.project.springconfig.I18nConfig;
import com.company.project.util.I18nNamedMessageResolver;

/**
* Auto generated by Build.java,
* Source template file: ${sourceTemplateFile},
* Please do not modify it directly.
*
* if has error, you can delete this file.
*/
@Component
public class I18nKeys implements MessageSourceAware{

	public static I18nNamedMessageResolver messageSource;
	
	static {
		init();
	}
	
	private static void init() {
		MessageSource ms = new I18nConfig().messageSource();
		new I18nKeys().setMessageSource(ms);
	}
	
	@Override
	public void setMessageSource(MessageSource value) {
		messageSource = new I18nNamedMessageResolver(value);
	}

	private static String getNamedMessage(String code, String... keyValuePairs) {
		return messageSource.getNamedMessage(code,keyValuePairs);
	}
	
<#list i18nEnMap?keys as key>

	<#assign newKey = key?replace('.', '_')?replace('-', '_')>
	/**
	* en: ${i18nEnMap[key]} <br/>
	* zh_CN: ${i18nZhCNMap[key]}
	*/
	private static String i18n_${newKey} = "${key}";
</#list>

<#list i18nEnMap?keys as key>

	<#assign newKey = key?replace('.', '_')?replace('-', '_')>
	<#assign messageParams = i18nMessageParamMap[key]>
	/**
	* en: ${i18nEnMap[key]} <br/>
	* zh_CN: ${i18nZhCNMap[key]}
	*/
	public static String i18n_${newKey}(<#list messageParams?keys as param>String ${param}<#if param_has_next>,</#if></#list>){
		String[] params = new String[]{<#list messageParams?keys as param>"${param}",${param}<#if param_has_next>,</#if></#list>};
		return getNamedMessage(i18n_${newKey},params);
	}
</#list>
}