​​​​############################
# dataSource
############################

spring.datasource​​.dynamic​​.datasource.master.url=jdbc:mysql://107.173.159.122:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
​​​​spring.datasource​​.dynamic​​.datasource.master.username=admin3
​​​​spring.datasource​​.dynamic​​.datasource.master.password=dfdddddfhjjg23fasdfsdfssdtestpwd
  
# slave_1数据源配置  
​​​​spring.datasource​​.dynamic​​.datasource.slave_1.url=jdbc:mysql://107.173.159.122:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
​​​​spring.datasource​​.dynamic​​.datasource.slave_1.username=admin3
​​​​spring.datasource​​.dynamic​​.datasource.slave_1.password=dfdddddfhjjg23fasdfsdfssdtestpwd

